// Generated by CoffeeScript 1.6.3
addEventListener('load', function() {
  VK.init({
    apiId: 2830838,
    onlyWidgets: true
  });
  return VK.Widgets.Comments('vk_comments', {
    limit: 20,
    width: 520,
    attach: '*'
  });
});
